@startuml
participant 信息系统
actor 读者
actor 图书管理员
activate 读者
读者 -> 信息系统:输入书名
activate 信息系统
信息系统 -> 读者:返回查询信息
读者 -> 信息系统:确认借阅
信息系统 -> 读者:检查读者信息，是否符合借阅条件并让读者填写取书时间
读者 -> 信息系统:填写取书时间
activate 图书管理员
信息系统 -> 图书管理员:同时管理员准备书籍
读者 -> 图书管理员:取书
@enduml